### PR TITLE
[CIP-1662] Add local-sys port to reset-vector selection

### PR DESCRIPTION
**Pull request by bsousi5**

### CODE REVIEW

**Comment by bsousi5** [comment]
@mmjconolly any idea how to fix this python lint error?

**Comment by mmjconolly** [comment]
> @mmjconolly any idea how to fix this python lint error?

Not sure, might be worth asking in the python slack channel

**Comment by richardxia** [comment]
I can say with very high confidence that the actual diff here has nothing to do with the lint error.

It looks like the version of [pylint is completely unpinned in requirements.txt](https://github.com/sifive/devicetree-overlay-generator/blob/fd99b125c00c62d0bd3bce25518b8a7b7c139421/requirements.txt#L2), meaning that every time a new version of pylint is published, this CI will install the newest version, which may add new lint rules. You may want to pin a specific version of pylint to get this to pass.

**Review by mwachs5 — APPROVED** [review]
from a what-this-is-doing perspective it SEEMS like it does what we said in the ticket

**Comment by bsousi5** [comment]
> I can say with very high confidence that the actual diff here has nothing to do with the lint error.
> 
> It looks like the version of [pylint is completely unpinned in requirements.txt](https://github.com/sifive/devicetree-overlay-generator/blob/fd99b125c00c62d0bd3bce25518b8a7b7c139421/requirements.txt#L2), meaning that every time a new version of pylint is published, this CI will install the newest version, which may add new lint rules. You may want to pin a specific version of pylint to get this to pass.

Thanks @richardxia . Very happy to able to chime in. Any idea what pylon version it was using previously.
I was going to merge because the Lint errors are unrelated, but want to avoid other follow up PRs hitting the same issue.

**Comment by richardxia** [comment]
> Any idea what pylon version it was using previously.

You could try cross referencing the date of the last time a build succeeded with the release history of the pylint project to get a rough estimate of what version was the latest at that moment in time. Failing that, you could just try installing older versions of that project until it succeeds.

This is an example of why I prefer to keep package lock files with the fully specified, concrete versions of all transitive dependencies checked into version control.

**Comment by bsousi5** [comment]
> > Any idea what pylon version it was using previously.
> 
> You could try cross referencing the date of the last time a build succeeded with the release history of the pylint project to get a rough estimate of what version was the latest at that moment in time. Failing that, you could just try installing older versions of that project until it succeeds.
> 
> This is an example of why I prefer to keep package lock files with the fully specified, concrete versions of all transitive dependencies checked into version control.

Ok thanks. Trying to do that now

**Pull request merged**
